---
- hosts: mywebserver
  become: yes
  tasks:
   - name: i want to install webserver on ubuntu nodes
     service:
        name: "{{myjavapackonubuntu}}"
        state: present
     when: ansible_os_family =="Debian"  

   - name: i want to install webserver on ubuntu nodes
     ansible.builtin.dnf:
        name: "{{myjavapackonRedHat}}"
        state: present
     when: ansible_os_family =="RedHat" 

   