---
- hosts: 172.31.34.235
  become: yes
  tasks: 
  - include_tasks: newfile.yml
  - name: i want to install webserver
    apt:
      name: apache2

  - name: copy index file into node side
    copy:
      src: myindex
      dest: C:\Users\BISWAMOHAN SAMAL\Desktop\ANSPLAYBOK\myindex