---
- hosts: 172.31.34.235
  become: yes
  tasks: 
  - include_tasks: newfile.yml
  - name: i want to install webserver
    apt:
      name: apache2

  - name: copy index file into node side
    copy:
      src: myindex
      dest: /var/www/html/index.html

  - name: i want download internet file
    ansible.builtin.get_url:
       url: http://example.com/path/file.conf
       dest: /etc/foo.conf
    force_basic_auth: yes
