---
- name: download tomcat tar file
  get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20-windows-x86.zip
     dest: /home/ubuntu/apache-tomcat-10.0.20
     force_basic_auth: yes

- name: crete a floder
  file:
    path: /opt/tomcat
    state: directory

- name: i want to extract tar file
  command:
      cmd: sudo tar /home/ubuntu/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/LICENCE
      