---
- name: copy tomcat-user xml file into node side
  templates:
    src: templates/mytomcatuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy context file into node side
  templates:
      src:  templates/mytomcontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml


- name: copy host context file into node side
  templates:
      src:  templates/myhostcontext.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml